# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [3]:
import numpy as np


In [5]:
# Step 2: Initialize Parameters
def initialize_parameters():
    # Seed the random number generator for reproducibility
    np.random.seed(1)
    # Initialize weights and biases for the first layer (3 neurons, 2 inputs)
    W1 = np.random.randn(3, 2) * 0.01
    b1 = np.zeros((3, 1))
    # Initialize weights and biases for the second layer (1 neuron, 3 inputs)
    W2 = np.random.randn(1, 3) * 0.01
    b2 = np.zeros((1, 1))
    return W1, b1, W2, b2

In [6]:
# Function to print the parameters in a pretty format (optional)
def print_parameters(W1, b1, W2, b2):
    print("W1 (weights for the first layer):")
    print(W1)
    print("\nb1 (biases for the first layer):")
    print(b1)
    print("\nW2 (weights for the second layer):")
    print(W2)
    print("\nb2 (biases for the second layer):")
    print(b2)

# Initialize parameters
W1, b1, W2, b2 = initialize_parameters()

# Print parameters in a pretty format
print_parameters(W1, b1, W2, b2)

W1 (weights for the first layer):
[[ 0.01624345 -0.00611756]
 [-0.00528172 -0.01072969]
 [ 0.00865408 -0.02301539]]

b1 (biases for the first layer):
[[0.]
 [0.]
 [0.]]

W2 (weights for the second layer):
[[ 0.01744812 -0.00761207  0.00319039]]

b2 (biases for the second layer):
[[0.]]


In [7]:
def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

def relu(Z):
    return np.maximum(0, Z)

def relu_derivative(Z):
    return Z > 0



In [12]:
# Step 4: Forward Propagation
def forward_propagation(X, W1, b1, W2, b2):
    # Compute linear combination for first layer
    Z1 = np.dot(W1, X) + b1
    # Apply ReLU activation function
    A1 = relu(Z1)
    # Compute linear combination for second layer
    Z2 = np.dot(W2, A1) + b2
    # Apply sigmoid activation function
    A2 = sigmoid(Z2)
    return Z1, A1, Z2, A2



In [13]:
def predict(X, W1, b1, W2, b2):
    # Forward propagation
    _, _, _, A2 = forward_propagation(X, W1, b1, W2, b2)
    # Convert probabilities to binary predictions
    predictions = (A2 > 0.5)
    return predictions


In [17]:
from sklearn.datasets import make_moons

# Create a dataset
X, Y = make_moons(n_samples=100, noise=0.2)
X = X.T

# Predict
predictions = predict(X, W1, b1, W2, b2)
print(X)
print(predictions)

[[ 1.72410727e+00 -3.94977018e-01  7.58141660e-01  1.71204266e+00
   1.46628045e+00 -1.02479511e+00  5.00299538e-01  2.00731463e+00
  -3.10131835e-01 -8.91327646e-01  8.44953570e-01  1.19648189e+00
   1.40913745e+00  5.93260275e-01  8.77833231e-01  3.23219372e-01
   1.10505249e-03  1.69788683e+00  5.32414375e-01  2.01978845e+00
  -7.08290702e-01  6.92102782e-01  1.83542726e+00  7.26186025e-01
  -1.13396399e+00 -8.01805177e-02 -2.92145026e-01  1.88232626e+00
   9.10316077e-01 -9.91386394e-01  1.07531817e+00  8.03209228e-02
   8.94768095e-01  1.16028819e+00  4.74940799e-02  2.08839305e-01
   1.30641892e+00 -1.13389015e+00  1.96042149e+00  1.58152039e+00
   6.86716793e-01  2.07787574e+00  6.06204427e-01  6.91723761e-01
   6.91661456e-01  6.08280995e-01  1.01187716e-01 -9.90912413e-01
  -1.22726423e-01 -4.43225584e-02  2.23237471e-01  1.89556733e+00
   7.71322875e-01  1.39918068e+00  2.05951812e-01  1.36094082e+00
  -2.87750044e-01  1.77879817e-01  5.76788066e-01  1.04680260e+00
   1.66933